id: PC89003DE
initial_creation_type: ocr
source_metadata:
  volumes:
    8da3a59e4ec74c42ae77f22a4706a77f:
      base_file: v037.txt
      image_group_id: I1PD95882
      title: ཡན་ལག་བདུན་པའི་སྒྲུབ་ཐབས།
      total_pages: 1379
      volume_number: 37
